micronaut:
  application:
    name: pizzaByte
datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pizza_byte
flyway:
  datasources:
    default:
      enabled: true
redis.uri: redis://localhost
